// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// logspace_addcpp
double logspace_addcpp(double logx, double logy);
RcppExport SEXP _schnapps_logspace_addcpp(SEXP logxSEXP, SEXP logySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type logx(logxSEXP);
    Rcpp::traits::input_parameter< double >::type logy(logySEXP);
    rcpp_result_gen = Rcpp::wrap(logspace_addcpp(logx, logy));
    return rcpp_result_gen;
END_RCPP
}
// viterbi
NumericVector viterbi(NumericMatrix emission, NumericMatrix transition, NumericVector observations);
RcppExport SEXP _schnapps_viterbi(SEXP emissionSEXP, SEXP transitionSEXP, SEXP observationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type emission(emissionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observations(observationsSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi(emission, transition, observations));
    return rcpp_result_gen;
END_RCPP
}
// viterbi_probs
NumericVector viterbi_probs(NumericMatrix emission, NumericMatrix transition, NumericVector observations);
RcppExport SEXP _schnapps_viterbi_probs(SEXP emissionSEXP, SEXP transitionSEXP, SEXP observationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type emission(emissionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observations(observationsSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi_probs(emission, transition, observations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_schnapps_logspace_addcpp", (DL_FUNC) &_schnapps_logspace_addcpp, 2},
    {"_schnapps_viterbi", (DL_FUNC) &_schnapps_viterbi, 3},
    {"_schnapps_viterbi_probs", (DL_FUNC) &_schnapps_viterbi_probs, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_schnapps(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
