// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logspace_addcpp
double logspace_addcpp(double logx, double logy);
RcppExport SEXP _signals_logspace_addcpp(SEXP logxSEXP, SEXP logySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type logx(logxSEXP);
    Rcpp::traits::input_parameter< double >::type logy(logySEXP);
    rcpp_result_gen = Rcpp::wrap(logspace_addcpp(logx, logy));
    return rcpp_result_gen;
END_RCPP
}
// viterbi
NumericVector viterbi(NumericMatrix emission, NumericMatrix transition, NumericVector observations);
RcppExport SEXP _signals_viterbi(SEXP emissionSEXP, SEXP transitionSEXP, SEXP observationsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type emission(emissionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type transition(transitionSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type observations(observationsSEXP);
    rcpp_result_gen = Rcpp::wrap(viterbi(emission, transition, observations));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_signals_logspace_addcpp", (DL_FUNC) &_signals_logspace_addcpp, 2},
    {"_signals_viterbi", (DL_FUNC) &_signals_viterbi, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_signals(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
