# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
logspace_addcpp <- function(logx, logy) {
    .Call('_schnapps_logspace_addcpp', PACKAGE = 'schnapps', logx, logy)
}

#' @export
myviterbicpp <- function(emission, transition, observations) {
    .Call('_schnapps_myviterbicpp', PACKAGE = 'schnapps', emission, transition, observations)
}

