# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logspace_addcpp <- function(logx, logy) {
    .Call('_schnapps_logspace_addcpp', PACKAGE = 'schnapps', logx, logy)
}

viterbi <- function(emission, transition, observations) {
    .Call('_schnapps_viterbi', PACKAGE = 'schnapps', emission, transition, observations)
}

viterbi_probs <- function(emission, transition, observations) {
    .Call('_schnapps_viterbi_probs', PACKAGE = 'schnapps', emission, transition, observations)
}

