# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.PAT }}
      R_KEEP_PKG_SOURCE: yes
    steps:
      - uses: actions/checkout@v3
      
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          
      - if: runner.os == 'macOS'
        uses: Homebrew/actions/setup-homebrew@master
        run: brew install --cask xquartz
        
      - uses: r-lib/actions/setup-pandoc@v2
      
      - name: Install cairo
        run: brew install cairo
        
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck, any::XML
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          error-on: '"error"'
